version: '3'

services:
  web:
    image: dockerregistry.tailcall.net/first/misp
    depends_on:
      - db
    container_name: misp_web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/wait-for-it.sh:/usr/local/bin/wait-for-it.sh:ro
      - /dev/urandom:/dev/random
      - ${DATA_DIR:-./data}/web:/var/www/MISP
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-misp_db}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL:-admin@admin.test}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE:-admin}
      - MISP_BASEURL=${MISP_BASEURL:-https://localhost}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST:-relay.fqdn}
      - TIMEZONE=${TIMEZONE:-UTC}
    entrypoint: "wait-for-it.sh -t 0 -h ${MYSQL_HOST:-misp_db} -p 3306 -- /run.sh"

  db:
    container_name: misp_db
    image: mysql/mysql-server:5.7
    hostname: ${MYSQL_HOST:-misp_db}
    restart: unless-stopped
    volumes:
      - ${DATA_DIR:-./data}/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-misp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-misp}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-misp}

volumes:
  web:
  db:
